// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using AniGoldShop.Inferastructure.Data.Common.Configuration;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public  class AgentZonesConfiguration : BaseEntityConfiguration<AgentZones>
    {
        public override void Configure(EntityTypeBuilder<AgentZones> entity)
        {
            entity.HasKey(e => e.AgentZoneId);

            entity.Property(e => e.AgentZoneId).ValueGeneratedNever();

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.HasOne(d => d.Agent)
                .WithMany(p => p.AgentZones)
                .HasForeignKey(d => d.AgentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AgentZones_Agents");

            entity.HasOne(d => d.City)
                .WithMany(p => p.AgentZones)
                .HasForeignKey(d => d.CityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AgentZones_Cities");

            entity.HasOne(d => d.Province)
                .WithMany(p => p.AgentZones)
                .HasForeignKey(d => d.ProvinceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AgentZones_Provinces");

        }

    }
}
