// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using AniGoldShop.Inferastructure.Data.Common.Configuration;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public class BlogGroupsConfiguration : BaseEntityConfiguration<BlogGroups>
    {
        public override void Configure(EntityTypeBuilder<BlogGroups> entity)
        {
            entity.HasKey(e => e.BlogGroupId);

            entity.Property(e => e.BlogGroupId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.BlogGroupName)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.BlogGroupTitle)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_BlogGroups_BlogGroups1");


        }

    
    }
}
