// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using AniGoldShop.Inferastructure.Data.Common.Configuration;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public class CitiesConfiguration : BaseEntityConfiguration<Cities>
    {
        public override void Configure(EntityTypeBuilder<Cities> entity)
        {
            entity.HasKey(e => e.CityId);

            entity.Property(e => e.CityId).ValueGeneratedNever();

            entity.Property(e => e.CityName)
                .IsRequired()
                .HasMaxLength(300);

            entity.Property(e => e.CityTitle)
                .IsRequired()
                .HasMaxLength(300);

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.HasOne(d => d.Province)
                .WithMany(p => p.Cities)
                .HasForeignKey(d => d.ProvinceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cities_Provinces");

        }

    }
}
