// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using AniGoldShop.Inferastructure.Data.Common.Configuration;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public  class FactorItemsConfiguration  : BaseEntityConfiguration<FactorItems>
    {
        public override void Configure(EntityTypeBuilder<FactorItems> entity)
        {
            entity.HasKey(e => e.FactorItemId);

            entity.Property(e => e.FactorItemId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.FactorItemCquantity).HasColumnName("FactorItemCQuantity");

            entity.Property(e => e.FactorItemGquantity).HasColumnName("FactorItemGQuantity");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.HasOne(d => d.Factor)
                .WithMany(p => p.FactorItems)
                .HasForeignKey(d => d.FactorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FactorItems_Factors");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.FactorItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FactorItems_Products");

        }

    }
}
