// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using AniGoldShop.Inferastructure.Data.Common.Configuration;
namespace AniGoldShop.Domain.Entities.Configurations
{
    public class PayTypesConfiguration  : BaseEntityConfiguration<PayTypes>
    {
        public override void Configure(EntityTypeBuilder<PayTypes> entity)
        {
            entity.HasKey(e => e.PayTypeId);

            entity.Property(e => e.PayTypeId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.Property(e => e.PayTypeName)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.PayTypeTitle)
                .IsRequired()
                .HasMaxLength(500);

         
        }

    }
}
