// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using AniGoldShop.Inferastructure.Data.Common.Configuration;
namespace AniGoldShop.Domain.Entities.Configurations
{
    public  class PriceTypesConfiguration  : BaseEntityConfiguration<PriceTypes>
    {
        public override void Configure(EntityTypeBuilder<PriceTypes> entity)
        {
            entity.HasKey(e => e.PriceTypeId);

            entity.Property(e => e.PriceTypeId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.Property(e => e.PriceTypeInfo).IsRequired();

            entity.Property(e => e.PriceTypeName)
                .IsRequired()
                .HasMaxLength(500);

           
        }

    }
}
