// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using AniGoldShop.Inferastructure.Data.Common.Configuration;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public class ProvincesConfiguration : BaseEntityConfiguration<Provinces>
    {
        public override void Configure(EntityTypeBuilder<Provinces> entity)
        {
            entity.HasKey(e => e.ProvinceId);

            entity.Property(e => e.ProvinceId).ValueGeneratedNever();

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.Property(e => e.ProvinceName)
                .IsRequired()
                .HasMaxLength(300);

            entity.Property(e => e.ProvinceTitle)
                .IsRequired()
                .HasMaxLength(300);

        }

    }
}
