// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using AniGoldShop.Inferastructure.Data.Common.Configuration;
namespace AniGoldShop.Domain.Entities.Configurations
{
    public  class UsersConfiguration  : BaseEntityConfiguration<Users>
    {
        public override void Configure(EntityTypeBuilder<Users> entity)
        {
            entity.HasKey(e => e.UserId);

            entity.Property(e => e.UserId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.Property(e => e.UserAddress).HasMaxLength(500);

            entity.Property(e => e.UserCellPhone).HasMaxLength(50);

            entity.Property(e => e.UserEmail).HasMaxLength(500);

            entity.Property(e => e.UserFullName)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.UserNationalId).HasMaxLength(10);

            entity.Property(e => e.UserPassword)
                .IsRequired()
                .IsUnicode(false);

            entity.Property(e => e.UserUsername)
                .IsRequired()
                .HasMaxLength(50);

   
        }

    }
}
