// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public class BlogGroups:BaseEntity
    {
        public BlogGroups()
        {
            Blogs = new HashSet<Blogs>();
            InverseParent = new HashSet<BlogGroups>();
        }

        public Guid BlogGroupId { get; set; }
        public Guid? ParentId { get; set; }
        public string BlogGroupName { get; set; }
        public string BlogGroupTitle { get; set; }
        public string BlogGroupIcon { get; set; }
        public virtual BlogGroups Parent { get; set; }
        public virtual ICollection<Blogs> Blogs { get; set; }
        public virtual ICollection<BlogGroups> InverseParent { get; set; }
    }
}