// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using AniGoldShop.Domain.Entities;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public  class Blogs:BaseEntity
    {
        public Guid BlogId { get; set; }
        public Guid? BlogGroupId { get; set; }
        public string BlogTitle { get; set; }
        public string BlogSummary { get; set; }
        public string BlogImages { get; set; }
        public string BlogText { get; set; }
        public Guid BlogAuthor { get; set; }
        public string BlogTags { get; set; }
        public virtual Users BlogAuthorNavigation { get; set; }
        public virtual BlogGroups BlogGroup { get; set; }
    }
}