// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public  class Cities:BaseEntity
    {
        public Cities()
        {
            AgentZones = new HashSet<AgentZones>();
            Factors = new HashSet<Factors>();
        }

        public int CityId { get; set; }
        public int ProvinceId { get; set; }
        public string CityName { get; set; }
        public string CityTitle { get; set; }

        public virtual Provinces Province { get; set; }
        public virtual ICollection<AgentZones> AgentZones { get; set; }
        public virtual ICollection<Factors> Factors { get; set; }
    }
}