// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public  class PayTypes : BaseEntity
    {
        public PayTypes()
        {
            Factors = new HashSet<Factors>();
        }

        public Guid PayTypeId { get; set; }
        public string PayTypeName { get; set; }
        public string PayTypeTitle { get; set; }

        public virtual ICollection<Factors> Factors { get; set; }
    }
}