// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public  class PriceTypes : BaseEntity
    {
        public PriceTypes()
        {
            Products = new HashSet<Products>();
        }

        public Guid PriceTypeId { get; set; }
        public string PriceTypeName { get; set; }
        public string PriceTypeInfo { get; set; }

        public virtual ICollection<Products> Products { get; set; }
    }
}