// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public class Roles : BaseEntity
    {
        public Roles()
        {
            UserRoles = new HashSet<UserRoles>();
        }

        public Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleImage { get; set; }

        public virtual ICollection<UserRoles> UserRoles { get; set; }
    }
}