// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public  class SendInfos : BaseEntity
    {
        public SendInfos()
        {
            Factors = new HashSet<Factors>();
        }

        public Guid SentInfoId { get; set; }

        public virtual ICollection<Factors> Factors { get; set; }
    }
}