// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public class Settings:BaseEntity
    {
        public Guid SettingId { get; set; }
        public string SettingTitle { get; set; }
        public string SettingKey { get; set; }
        public string SettingValue { get; set; }
        public byte SettingType { get; set; }

    }
}