// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public  class Slides:BaseEntity
    {
        public Guid SlideId { get; set; }
        public short SlideType { get; set; }
        public DateTime? SlideStart { get; set; }
        public DateTime? SlideEnd { get; set; }
        public short SlideFileType { get; set; }
        public string SlideFile { get; set; }
        public string SlideLink { get; set; }
        public string SlideHtml { get; set; }

    }
}