// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public  class Specials:BaseEntity
    {
        public Guid SpecialId { get; set; }
        public Guid ProductId { get; set; }
        public DateTime? SpecialStart { get; set; }
        public DateTime? SpecialEnd { get; set; }
        public short SpecialType { get; set; }

        public virtual Products Product { get; set; }
    }
}