// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AniGoldShop.Domain.Common.BaseModels;
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public class Users : BaseEntity
    {
        public Users()
        {
            Blogs = new HashSet<Blogs>();
            Factors = new HashSet<Factors>();
            UserRoles = new HashSet<UserRoles>();
        }

        public Guid UserId { get; set; }
        public string UserFullName { get; set; }
        public string UserEmail { get; set; }
        public string UserCellPhone { get; set; }
        public string UserAddress { get; set; }
        public string UserNationalId { get; set; }
        public string UserUsername { get; set; }
        public string UserPassword { get; set; }

        public virtual ICollection<Blogs> Blogs { get; set; }
        public virtual ICollection<Factors> Factors { get; set; }
        public virtual ICollection<UserRoles> UserRoles { get; set; }
    }
}