// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public partial class AgentsConfiguration : IEntityTypeConfiguration<Agents>
    {
        public void Configure(EntityTypeBuilder<Agents> entity)
        {
            entity.HasKey(e => e.AgentId);

            entity.Property(e => e.AgentId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.AgentName).IsRequired();

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.HasOne(d => d.UserRole)
                .WithMany(p => p.Agents)
                .HasForeignKey(d => d.UserRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Agents_UserRoles");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Agents> entity);
    }
}
