// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public partial class BlogsConfiguration : IEntityTypeConfiguration<Blogs>
    {
        public void Configure(EntityTypeBuilder<Blogs> entity)
        {
            entity.HasKey(e => e.BlogId);

            entity.Property(e => e.BlogId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.BlogSummary).IsRequired();

            entity.Property(e => e.BlogTitle)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.HasOne(d => d.BlogAuthorNavigation)
                .WithMany(p => p.Blogs)
                .HasForeignKey(d => d.BlogAuthor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Blogs_Users");

            entity.HasOne(d => d.BlogGroup)
                .WithMany(p => p.Blogs)
                .HasForeignKey(d => d.BlogGroupId)
                .HasConstraintName("FK_Blogs_BlogGroups");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Blogs> entity);
    }
}
