// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public partial class ProductGroupsConfiguration : IEntityTypeConfiguration<ProductGroups>
    {
        public void Configure(EntityTypeBuilder<ProductGroups> entity)
        {
            entity.HasKey(e => e.ProductGroupId);

            entity.Property(e => e.ProductGroupId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.Property(e => e.ProductGroupName)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.ProductGroupTitle)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.Parent)
                .WithMany(p => p.InverseParent)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_ProductGroups_ProductGroups1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductGroups> entity);
    }
}
