// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace AniGoldShop.Domain.Entities.Configurations
{
    public partial class SlidesConfiguration : IEntityTypeConfiguration<Slides>
    {
        public void Configure(EntityTypeBuilder<Slides> entity)
        {
            entity.HasKey(e => e.SlideId);

            entity.Property(e => e.SlideId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.Lang)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.Property(e => e.SlideFile).IsRequired();

            entity.Property(e => e.SlideHtml).HasColumnName("SlideHTML");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Slides> entity);
    }
}
