// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class AgentZones
    {
        public Guid AgentZoneId { get; set; }
        public Guid AgentId { get; set; }
        public int ProvinceId { get; set; }
        public int CityId { get; set; }
        public DateTime? AgentZoneStart { get; set; }
        public DateTime? AgentZoneEnd { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual Agents Agent { get; set; }
        public virtual Cities City { get; set; }
        public virtual Provinces Province { get; set; }
    }
}