// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AniGoldShop.Domain.Entities.Configurations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
#nullable disable

#nullable disable

namespace AniGoldShop.Domain.Entities
{
    public partial class AnigoldContext : DbContext
    {
        public AnigoldContext()
        {
        }

        public AnigoldContext(DbContextOptions<AnigoldContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AgentZones> AgentZones { get; set; }
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<BlogGroups> BlogGroups { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<FactorItems> FactorItems { get; set; }
        public virtual DbSet<Factors> Factors { get; set; }
        public virtual DbSet<PaidInfos> PaidInfos { get; set; }
        public virtual DbSet<PayTypes> PayTypes { get; set; }
        public virtual DbSet<PriceTypes> PriceTypes { get; set; }
        public virtual DbSet<ProductGroups> ProductGroups { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Provinces> Provinces { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SendInfos> SendInfos { get; set; }
        public virtual DbSet<SendTypes> SendTypes { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Slides> Slides { get; set; }
        public virtual DbSet<Specials> Specials { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.AgentZonesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AgentsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BlogGroupsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BlogsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CitiesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.FactorItemsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.FactorsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PaidInfosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PayTypesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PriceTypesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductGroupsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProvincesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RolesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SendInfosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SendTypesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SettingsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SlidesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SpecialsConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserRolesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsersConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
