// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class BlogGroups
    {
        public BlogGroups()
        {
            Blogs = new HashSet<Blogs>();
            InverseParent = new HashSet<BlogGroups>();
        }

        public Guid BlogGroupId { get; set; }
        public Guid? ParentId { get; set; }
        public string BlogGroupName { get; set; }
        public string BlogGroupTitle { get; set; }
        public string BlogGroupIcon { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual BlogGroups Parent { get; set; }
        public virtual ICollection<Blogs> Blogs { get; set; }
        public virtual ICollection<BlogGroups> InverseParent { get; set; }
    }
}