// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class PayTypes
    {
        public PayTypes()
        {
            Factors = new HashSet<Factors>();
        }

        public Guid PayTypeId { get; set; }
        public string PayTypeName { get; set; }
        public string PayTypeTitle { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual ICollection<Factors> Factors { get; set; }
    }
}