// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class PriceTypes
    {
        public PriceTypes()
        {
            Products = new HashSet<Products>();
        }

        public Guid PriceTypeId { get; set; }
        public string PriceTypeName { get; set; }
        public string PriceTypeInfo { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual ICollection<Products> Products { get; set; }
    }
}