// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class ProductGroups
    {
        public ProductGroups()
        {
            InverseParent = new HashSet<ProductGroups>();
            Products = new HashSet<Products>();
        }

        public Guid ProductGroupId { get; set; }
        public Guid? ParentId { get; set; }
        public string ProductGroupName { get; set; }
        public string ProductGroupTitle { get; set; }
        public string ProductGroupIcon { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual ProductGroups Parent { get; set; }
        public virtual ICollection<ProductGroups> InverseParent { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}