// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class Products
    {
        public Products()
        {
            FactorItems = new HashSet<FactorItems>();
            Specials = new HashSet<Specials>();
        }

        public Guid ProductId { get; set; }
        public int ProductCode { get; set; }
        public Guid ProductGroupId { get; set; }
        public string ProductName { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDesc { get; set; }
        public string ProductJsonDesc { get; set; }
        public decimal ProductWeight { get; set; }
        public short ProductCutting { get; set; }
        public Guid PriceTypeId { get; set; }
        public string ProductPriceInfo { get; set; }
        public string ProductImages { get; set; }
        public int ProductCount { get; set; }
        public long? ProductDiscount { get; set; }
        public DateTime? ProductDiscountStart { get; set; }
        public DateTime? ProductDiscountEnd { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual PriceTypes PriceType { get; set; }
        public virtual ProductGroups ProductGroup { get; set; }
        public virtual ICollection<FactorItems> FactorItems { get; set; }
        public virtual ICollection<Specials> Specials { get; set; }
    }
}