// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class Provinces
    {
        public Provinces()
        {
            AgentZones = new HashSet<AgentZones>();
            Cities = new HashSet<Cities>();
            Factors = new HashSet<Factors>();
        }

        public int ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public string ProvinceTitle { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual ICollection<AgentZones> AgentZones { get; set; }
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual ICollection<Factors> Factors { get; set; }
    }
}