// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class Settings
    {
        public Guid SettingId { get; set; }
        public string SettingTitle { get; set; }
        public string SettingKey { get; set; }
        public string SettingValue { get; set; }
        public byte SettingType { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public int? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}