// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class Slides
    {
        public Guid SlideId { get; set; }
        public short SlideType { get; set; }
        public DateTime? SlideStart { get; set; }
        public DateTime? SlideEnd { get; set; }
        public short SlideFileType { get; set; }
        public string SlideFile { get; set; }
        public string SlideLink { get; set; }
        public string SlideHtml { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}