// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class Specials
    {
        public Guid SpecialId { get; set; }
        public Guid ProductId { get; set; }
        public DateTime? SpecialStart { get; set; }
        public DateTime? SpecialEnd { get; set; }
        public short SpecialType { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual Products Product { get; set; }
    }
}