// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AniGoldShop.Domain.Entities
{
    public partial class Users
    {
        public Users()
        {
            Blogs = new HashSet<Blogs>();
            Factors = new HashSet<Factors>();
            UserRoles = new HashSet<UserRoles>();
        }

        public Guid UserId { get; set; }
        public string UserFullName { get; set; }
        public string UserEmail { get; set; }
        public string UserCellPhone { get; set; }
        public string UserAddress { get; set; }
        public string UserNationalId { get; set; }
        public string UserUsername { get; set; }
        public string UserPassword { get; set; }
        public DateTime CreateDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreateUser { get; set; }
        public Guid? ModifiedUser { get; set; }
        public long? Priority { get; set; }
        public string Lang { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public virtual ICollection<Blogs> Blogs { get; set; }
        public virtual ICollection<Factors> Factors { get; set; }
        public virtual ICollection<UserRoles> UserRoles { get; set; }
    }
}