//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniGoldShop.Application.Common.Localization.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextLocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextLocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AniGoldShop.Application.Common.Localization.Text.TextLocalizationResource", typeof(TextLocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation performed successfully.
        /// </summary>
        public static string authorization_succeeded {
            get {
                return ResourceManager.GetString("authorization succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has already been verified and activated.
        /// </summary>
        public static string before_confirmd_account {
            get {
                return ResourceManager.GetString("before confirmd account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone.
        /// </summary>
        public static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password change was successful.
        /// </summary>
        public static string changeUserPasswordSuccessfully {
            get {
                return ResourceManager.GetString("changeUserPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information is available.
        /// </summary>
        public static string Data_exist {
            get {
                return ResourceManager.GetString("Data exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information available.
        /// </summary>
        public static string Data_not_exist {
            get {
                return ResourceManager.GetString("Data not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string email_address_is_not_valid {
            get {
                return ResourceManager.GetString("email address is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Not Valid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch data successfully.
        /// </summary>
        public static string fetch_data_successfully {
            get {
                return ResourceManager.GetString("fetch data successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is not valid.
        /// </summary>
        public static string id_is_not_valid {
            get {
                return ResourceManager.GetString("id is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information review was performed.
        /// </summary>
        public static string Information_review_was_performed {
            get {
                return ResourceManager.GetString("Information review was performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration information completed successfully..
        /// </summary>
        public static string Insert_data_successfully {
            get {
                return ResourceManager.GetString("Insert data successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the uploaded file should not exceed 2 MB..
        /// </summary>
        public static string Maximum_upload_file {
            get {
                return ResourceManager.GetString("Maximum upload file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is not valid.
        /// </summary>
        public static string mobile_phone_number_is_not_valid {
            get {
                return ResourceManager.GetString("mobile phone number is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new password is not the same as repeating a password.
        /// </summary>
        public static string New_password_with_repeate_pssword_is_not_equal {
            get {
                return ResourceManager.GetString("New password with repeate pssword is not equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is invalid.
        /// </summary>
        public static string Old_password_is_not_valid {
            get {
                return ResourceManager.GetString("Old password is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mission accomplished.
        /// </summary>
        public static string operation_done_successfully {
            get {
                return ResourceManager.GetString("operation done successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and password repetition are not the same.
        /// </summary>
        public static string password_and_rePassword_not_is_equal {
            get {
                return ResourceManager.GetString("password and rePassword not is equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        public static string please_enter_your_name {
            get {
                return ResourceManager.GetString("please enter your name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string please_enter_your_password {
            get {
                return ResourceManager.GetString("please enter your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted reserved parent deleted successfully.
        /// </summary>
        public static string remove_expired_reserved_parent_successfully {
            get {
                return ResourceManager.GetString("remove expired reserved parent successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value Is required.
        /// </summary>
        public static string RequiredValidation {
            get {
                return ResourceManager.GetString("RequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent campaign reservation successfully completed.
        /// </summary>
        public static string Reserve_parent_campaign_successfully {
            get {
                return ResourceManager.GetString("Reserve parent campaign successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The booked parent campaign has expired.
        /// </summary>
        public static string reserved_parent_campaign_in_expired {
            get {
                return ResourceManager.GetString("reserved parent campaign in expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was successful.
        /// </summary>
        public static string Send_email_successfully {
            get {
                return ResourceManager.GetString("Send email successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful sending of recovery code to user email.
        /// </summary>
        public static string SendRecoveryPasswordCodeToEmailSuccessfully {
            get {
                return ResourceManager.GetString("SendRecoveryPasswordCodeToEmailSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        public static string sent_email_successfully {
            get {
                return ResourceManager.GetString("sent email successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template not defined.
        /// </summary>
        public static string Template_email_for_x_is_not_define {
            get {
                return ResourceManager.GetString("Template email for x is not define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty.
        /// </summary>
        public static string the_userName_can_t_be_empty {
            get {
                return ResourceManager.GetString("the userName can\'t be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username has already been used by someone else.
        /// </summary>
        public static string the_userName_used_before_by_another {
            get {
                return ResourceManager.GetString("the userName used before by another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information successfully updated..
        /// </summary>
        public static string update_data_successfully {
            get {
                return ResourceManager.GetString("update data successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is not valid..
        /// </summary>
        public static string user_id_is_not_valid {
            get {
                return ResourceManager.GetString("user id is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is not valid.
        /// </summary>
        public static string user_name_or_password_is_invalid {
            get {
                return ResourceManager.GetString("user name or password is invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration completed successfully.
        /// </summary>
        public static string user_successfully_created {
            get {
                return ResourceManager.GetString("user successfully created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email has not registered before.
        /// </summary>
        public static string UserWithThisEmailNotRegisterBefore {
            get {
                return ResourceManager.GetString("UserWithThisEmailNotRegisterBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit confirmation error encountered.
        /// </summary>
        public static string withdrawal_Commit_with_error {
            get {
                return ResourceManager.GetString("withdrawal Commit with error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t request refund.
        /// </summary>
        public static string you_can_t_request_refund {
            get {
                return ResourceManager.GetString("you can\'t request refund", resourceCulture);
            }
        }
    }
}
